if (!window.STRINGS) window.STRINGS = {};
STRINGS.fr = {
  headerSubtitle: 'Rééducation de l\'écriture',
  exercisesTitle: 'Pratiquer l\'écriture', exercisesSubtitle: 'Choisissez un type d\'exercice',
  disclaimer: '<strong>Outil de bien-être uniquement.</strong> ReWrite soutient la rééducation de l\'écriture mais n\'est pas un dispositif médical. Suivez toujours les conseils de votre ergothérapeute ou de votre équipe soignante.',
  exLettersTitle: 'Lettres individuelles', exLettersDesc: 'Tracez les lettres. Concentrez-vous sur la forme et la taille.',
  exNumbersTitle: 'Chiffres', exNumbersDesc: 'Pratiquez l\'écriture des chiffres 0–9.',
  exWordsTitle: 'Mots courants', exWordsDesc: 'Tracez des mots courts du quotidien.',
  exSentencesTitle: 'Phrases', exSentencesDesc: 'Écrivez des phrases complètes.',
  tipText: 'Conseil : Des sessions courtes quotidiennes (10–15 min) sont plus efficaces.',
  tracePrompt: 'Tracez soigneusement :', clearBtn: '↻ Effacer', submitBtn: '✓ Soumettre',
  nextBtn: 'Suivant →', finishBtn: 'Terminer ✓', exitBtn: '← Retour',
  summaryTitle: 'Session terminée', summarySubtitle: 'Bon travail — voici vos résultats',
  progressTitle: 'Votre progression', exportBtn: '📋 Exporter pour l\'ergothérapeute',
  aboutTitle: 'À propos', settingsTitle: 'Paramètres',
  tabExercises: 'Exercices', tabProgress: 'Progrès', tabAbout: 'Info', tabSettings: 'Réglages',
  excellent:'Excellent !',excellentMsg:'Beau tracé — continuez.',good:'Bon effort',goodMsg:'Bonne forme — essayez de rester plus proche du guide.',improving:'Continuez',improvingMsg:'Vous progressez — chaque tentative compte.',early:'Bravo d\'avoir essayé',earlyMsg:'La rééducation demande du temps et de la patience.',
  sumEncHigh:'Travail exceptionnel aujourd\'hui.',sumEncMid:'Bonne session.',sumEncLow:'Chaque session compte.',sumEncEarly:'Le plus important est de continuer à essayer.',
  // Progress & UI strings
  storageUnavailable: 'Stockage indisponible (navigation privée ?). La progression ne sera pas sauvegardée entre les sessions.',
  bandStrong: 'Solide',
  bandDeveloping: 'En progression',
  bandEarly: 'Stade initial',
  exerciseTypeLetters: 'Lettres',
  exerciseTypeNumbers: 'Chiffres',
  exerciseTypeWords: 'Mots',
  exerciseTypeSentences: 'Phrases',
  noExercises: 'Aucun exercice enregistré pour l\'instant.',
  noSessions: 'Aucune séance pour l\'instant — commencez la première depuis l\'onglet Exercices.',
  trendEmpty: 'Effectuez au moins deux séances pour voir votre tendance de progression.',
  trendHelp: 'Score moyen par séance dans le temps',
  exBreakdownTitle: 'Détail des exercices',
  exBreakdownDetail: 'exercices · Moy.',
  exBreakdownBest: 'Max.',
  confirmReset: 'Êtes-vous sûr de vouloir réinitialiser tous les progrès ? Cette action est irréversible.',
  sessionLogExercises: 'exercices',
};
