if (!window.STRINGS) window.STRINGS = {};
STRINGS.pt_br = {
  headerSubtitle: 'Reabilitação da escrita',
  exercisesTitle: 'Praticar escrita', exercisesSubtitle: 'Escolha um tipo de exercício para começar',
  disclaimer: '<strong>Apenas ferramenta de bem-estar.</strong> O ReWrite apoia a reabilitação da escrita mas não é um dispositivo médico. Siga sempre as orientações do seu terapeuta ocupacional.',
  exLettersTitle: 'Letras individuais', exLettersDesc: 'Trace letras. Foque na forma e no tamanho.',
  exNumbersTitle: 'Números', exNumbersDesc: 'Pratique escrever os dígitos 0–9.',
  exWordsTitle: 'Palavras comuns', exWordsDesc: 'Trace palavras curtas do dia a dia.',
  exSentencesTitle: 'Frases', exSentencesDesc: 'Escreva frases completas para ganhar resistência.',
  tipText: 'Dica: Sessões curtas diárias (10–15 min) são mais eficazes.',
  tracePrompt: 'Trace com cuidado:', clearBtn: '↻ Limpar', submitBtn: '✓ Enviar',
  nextBtn: 'Próximo →', finishBtn: 'Finalizar ✓', exitBtn: '← Voltar',
  summaryTitle: 'Sessão concluída', summarySubtitle: 'Bom trabalho — veja como foi',
  progressTitle: 'Seu progresso', exportBtn: '📋 Exportar para o terapeuta ocupacional',
  aboutTitle: 'Sobre o ReWrite', settingsTitle: 'Configurações',
  tabExercises: 'Exercícios', tabProgress: 'Progresso', tabAbout: 'Info', tabSettings: 'Config.',
  excellent:'Excelente!',excellentMsg:'Belo traçado — continue assim.',good:'Bom esforço',goodMsg:'Boa forma — tente ficar mais perto do guia.',improving:'Continue',improvingMsg:'Você está progredindo — cada tentativa conta.',early:'Parabéns por tentar',earlyMsg:'A reabilitação leva tempo e paciência.',
  sumEncHigh:'Trabalho excepcional hoje.',sumEncMid:'Boa sessão.',sumEncLow:'Cada sessão importa.',sumEncEarly:'O passo mais importante é continuar tentando.',
  // Progress & UI strings
  storageUnavailable: 'Armazenamento indisponível (navegação privada?). O progresso não será salvo entre sessões.',
  bandStrong: 'Sólido',
  bandDeveloping: 'Em desenvolvimento',
  bandEarly: 'Fase inicial',
  exerciseTypeLetters: 'Letras',
  exerciseTypeNumbers: 'Números',
  exerciseTypeWords: 'Palavras',
  exerciseTypeSentences: 'Frases',
  noExercises: 'Nenhum exercício registrado ainda.',
  noSessions: 'Ainda não há sessões — inicie a primeira pela aba Exercícios.',
  trendEmpty: 'Conclua pelo menos duas sessões para ver sua tendência de progresso.',
  trendHelp: 'Pontuação média por sessão ao longo do tempo',
  exBreakdownTitle: 'Detalhe de exercícios',
  exBreakdownDetail: 'exercícios · Méd.',
  exBreakdownBest: 'Máx.',
  confirmReset: 'Tem certeza de que deseja redefinir todo o progresso? Esta ação não pode ser desfeita.',
  sessionLogExercises: 'exercícios',
};
